### PR TITLE
Export stream

### PR DESCRIPTION
**Pull request by jamen**

### CODE REVIEW

**Comment by jamen** [comment]
So we can release minor for now?  I plan on publishing `pull-audio-gain` but I need the functional code released on npm.

**Comment by dy** [comment]
Lgtm!

**Comment by jamen** [comment]
I realized this would still be breaking, because we are missing `gain.setVolume` from previous version.

Should we:

 - Add `setVolume` (+ tests) and still release minor with stream?
 - Make package fully functional for major release, then release other packages?  Dropping `setVolume`

**Comment by jamen** [comment]
I just published it using the github repo as a dependency, so we can think about moving this package forward.

**Pull request closed without merging**
